import type { QuizSeed } from "./quiz.ts";

export const LECTURE_ANIMAUX: QuizSeed[] = [
  {
    passage: "Léa a un chat gris. Il dort sur le canapé.",
    prompt: "De quelle couleur est le chat ?",
    answer: "gris",
    distractors: ["blanc", "noir", "roux"],
  },
  {
    passage: "Le chien de Tom s'appelle Nino. Il aime courir dans le jardin.",
    prompt: "Comment s'appelle le chien ?",
    answer: "Nino",
    distractors: ["Tom", "Léa", "Léo"],
  },
  {
    passage: "Un oiseau bleu chante dans l'arbre. Il a trouvé des graines.",
    prompt: "Où chante l'oiseau ?",
    answer: "dans l'arbre",
    distractors: ["dans l'eau", "sur le toit", "sous le lit"],
  },
  {
    passage: "La vache mange de l'herbe verte. Elle vit dans un pré.",
    prompt: "Que mange la vache ?",
    answer: "de l'herbe",
    distractors: ["du pain", "des pommes", "du poisson"],
  },
  {
    passage: "Un poisson rouge nage dans le bocal. Il est tout petit.",
    prompt: "Où nage le poisson ?",
    answer: "dans le bocal",
    distractors: ["dans la mer", "dans le pré", "dans le nid"],
  },
  {
    passage: "Le lapin blanc a de longues oreilles. Il mange une carotte.",
    prompt: "Que mange le lapin ?",
    answer: "une carotte",
    distractors: ["une pomme", "du fromage", "du pain"],
  },
  {
    passage: "La poule a pondu un œuf. Les poussins courent derrière elle.",
    prompt: "Qu'a pondu la poule ?",
    answer: "un œuf",
    distractors: ["une noix", "une pomme", "un caillou"],
  },
  {
    passage: "Un lion dort sous un arbre. Il fait très chaud.",
    prompt: "Que fait le lion ?",
    answer: "il dort",
    distractors: ["il nage", "il chante", "il vole"],
  },
  {
    passage: "L'abeille butine une fleur jaune. Elle va faire du miel.",
    prompt: "Que va faire l'abeille ?",
    answer: "du miel",
    distractors: ["du pain", "un nid", "du fromage"],
  },
  {
    passage: "Le cheval noir galope dans le champ. Un enfant le regarde.",
    prompt: "De quelle couleur est le cheval ?",
    answer: "noir",
    distractors: ["blanc", "gris", "brun"],
  },
  {
    passage: "Une souris grise se cache sous la table. Le chat la cherche.",
    prompt: "Où se cache la souris ?",
    answer: "sous la table",
    distractors: ["sur le toit", "dans l'eau", "dans le lit"],
  },
  {
    passage: "Le dauphin saute hors de l'eau. Les enfants applaudissent.",
    prompt: "Qui saute hors de l'eau ?",
    answer: "le dauphin",
    distractors: ["le chat", "le cheval", "l'oiseau"],
  },
  {
    passage: "Un hibou ouvre de grands yeux. Il chasse la nuit.",
    prompt: "Quand chasse le hibou ?",
    answer: "la nuit",
    distractors: ["le matin", "à midi", "le soir tôt"],
  },
  {
    passage: "La grenouille verte saute dans la mare. Elle attrape une mouche.",
    prompt: "Où saute la grenouille ?",
    answer: "dans la mare",
    distractors: ["dans l'arbre", "sur le toit", "dans le sable"],
  },
  {
    passage: "Le mouton a une laine blanche. Le fermier le tond au printemps.",
    prompt: "De quelle couleur est la laine ?",
    answer: "blanche",
    distractors: ["noire", "grise", "brune"],
  },
  {
    passage: "Un papillon orange se pose sur une rose. Il ouvre ses ailes.",
    prompt: "Sur quoi se pose le papillon ?",
    answer: "une rose",
    distractors: ["un caillou", "un seau", "un banc"],
  },
];

export const LECTURE_ECOLE: QuizSeed[] = [
  {
    passage: "Marie range ses crayons dans sa trousse. La cloche va sonner.",
    prompt: "Où Marie range-t-elle ses crayons ?",
    answer: "dans sa trousse",
    distractors: ["dans son cartable", "sur le bureau", "sous la chaise"],
  },
  {
    passage: "Léo lit un livre de maths. Il compte jusqu'à vingt.",
    prompt: "Quel livre Léo lit-il ?",
    answer: "un livre de maths",
    distractors: ["un livre d'anglais", "une bande dessinée", "un cahier"],
  },
  {
    passage: "À la récré, les enfants jouent au ballon. Il fait beau.",
    prompt: "À quoi jouent les enfants ?",
    answer: "au ballon",
    distractors: ["aux dames", "au cache-cache", "à la marelle"],
  },
  {
    passage: "La maîtresse écrit au tableau. Les élèves copient la date.",
    prompt: "Que copient les élèves ?",
    answer: "la date",
    distractors: ["un dessin", "une chanson", "un poème"],
  },
  {
    passage: "Tom a oublié son goûter. Sa copine lui donne une pomme.",
    prompt: "Qu'est-ce que Tom a oublié ?",
    answer: "son goûter",
    distractors: ["son cartable", "son manteau", "ses clés"],
  },
  {
    passage: "Il y a trop de livres. Le cartable de Léa est trop lourd.",
    prompt: "Pourquoi le cartable est-il lourd ?",
    answer: "trop de livres",
    distractors: ["trop d'eau", "trop de sable", "trop de pain"],
  },
  {
    passage: "On chante une chanson en classe. Tout le monde est debout.",
    prompt: "Que fait la classe ?",
    answer: "elle chante",
    distractors: ["elle dort", "elle court", "elle mange"],
  },
  {
    passage: "Paul dessine une maison rouge. Il utilise un crayon de couleur.",
    prompt: "Que dessine Paul ?",
    answer: "une maison",
    distractors: ["un arbre", "un bateau", "un chat"],
  },
  {
    passage: "La cantine sert des pâtes aujourd'hui. Les enfants sont contents.",
    prompt: "Que sert-on à la cantine ?",
    answer: "des pâtes",
    distractors: ["du poisson", "une soupe", "des frites"],
  },
  {
    passage: "La classe est terminée. Nino range sa chaise.",
    prompt: "Que range Nino ?",
    answer: "sa chaise",
    distractors: ["son manteau", "ses livres", "son goûter"],
  },
  {
    passage: "On va à la bibliothèque. Chacun choisit un livre.",
    prompt: "Où va la classe ?",
    answer: "à la bibliothèque",
    distractors: ["à la piscine", "au gymnase", "au parc"],
  },
  {
    passage: "Elle a bien lu son texte. Inès a eu une étoile.",
    prompt: "Pourquoi Inès a-t-elle une étoile ?",
    answer: "elle a bien lu",
    distractors: ["elle a couru", "elle a chanté", "elle a dormi"],
  },
  {
    passage: "Le tableau est vert. La craie est blanche.",
    prompt: "De quelle couleur est le tableau ?",
    answer: "vert",
    distractors: ["blanc", "bleu", "noir"],
  },
  {
    passage: "On apprend une poésie. Il faut la réciter demain.",
    prompt: "Quand faut-il réciter la poésie ?",
    answer: "demain",
    distractors: ["hier", "ce soir", "lundi dernier"],
  },
  {
    passage: "Hugo a perdu sa gomme. Elle était dans sa trousse.",
    prompt: "Qu'a perdu Hugo ?",
    answer: "sa gomme",
    distractors: ["son stylo", "son cahier", "sa règle"],
  },
  {
    passage: "La classe part en sortie. On va visiter un musée.",
    prompt: "Que va visiter la classe ?",
    answer: "un musée",
    distractors: ["une ferme", "un château", "une plage"],
  },
];

export const LECTURE_MAISON: QuizSeed[] = [
  {
    passage: "Toute la famille a faim. Papa cuisine une soupe.",
    prompt: "Que cuisine papa ?",
    answer: "une soupe",
    distractors: ["un gâteau", "des pâtes", "un gratin"],
  },
  {
    passage: "Léa range sa chambre. Les jouets sont dans le coffre.",
    prompt: "Où sont les jouets ?",
    answer: "dans le coffre",
    distractors: ["sous le lit", "sur la table", "dans le jardin"],
  },
  {
    passage: "Le chat dort sur le tapis. Il fait une sieste.",
    prompt: "Où dort le chat ?",
    answer: "sur le tapis",
    distractors: ["sur le toit", "dans le frigo", "sous la voiture"],
  },
  {
    passage: "Maman arrose les plantes. Elles sont sur le balcon.",
    prompt: "Où sont les plantes ?",
    answer: "sur le balcon",
    distractors: ["dans la cave", "sous le lit", "dans le garage"],
  },
  {
    passage: "On mange à table. Il y a du pain et du fromage.",
    prompt: "Que mange-t-on avec le pain ?",
    answer: "du fromage",
    distractors: ["du savon", "du sable", "du papier"],
  },
  {
    passage: "Léo se brosse les dents. Il est dans la salle de bain.",
    prompt: "Où est Léo ?",
    answer: "dans la salle de bain",
    distractors: ["dans le jardin", "à l'école", "dans le bus"],
  },
  {
    passage: "La fenêtre de la cuisine est ouverte. Il entre de l'air frais.",
    prompt: "Quelle fenêtre est ouverte ?",
    answer: "celle de la cuisine",
    distractors: ["celle du grenier", "celle de l'école", "celle du garage"],
  },
  {
    passage: "Il commence à faire nuit. On allume la lampe.",
    prompt: "Pourquoi allume-t-on la lampe ?",
    answer: "il fait nuit",
    distractors: ["il pleut", "il neige", "il vente"],
  },
  {
    passage: "Le linge était mouillé. Il sèche sur le radiateur.",
    prompt: "Où sèche le linge ?",
    answer: "sur le radiateur",
    distractors: ["dans le frigo", "sous le tapis", "dans le four"],
  },
  {
    passage: "Tom met la table. Il y a quatre assiettes.",
    prompt: "Combien y a-t-il d'assiettes ?",
    answer: "quatre",
    distractors: ["deux", "six", "dix"],
  },
  {
    passage: "Le canapé est bleu. On s'assoit pour lire.",
    prompt: "De quelle couleur est le canapé ?",
    answer: "bleu",
    distractors: ["rouge", "vert", "jaune"],
  },
  {
    passage: "On range les chaussures dans l'entrée. Il ne faut pas les laisser au milieu.",
    prompt: "Où range-t-on les chaussures ?",
    answer: "dans l'entrée",
    distractors: ["dans le frigo", "sous l'oreiller", "dans la baignoire"],
  },
  {
    passage: "Le réveil sonne. Il est sept heures.",
    prompt: "Quelle heure est-il ?",
    answer: "sept heures",
    distractors: ["midi", "trois heures", "minuit"],
  },
  {
    passage: "Grand-mère tricote un pull. Il est rouge et chaud.",
    prompt: "Que tricote grand-mère ?",
    answer: "un pull",
    distractors: ["un gâteau", "un tapis", "un livre"],
  },
  {
    passage: "Toute la famille est rentrée. On ferme la porte à clé.",
    prompt: "Pourquoi ferme-t-on la porte ?",
    answer: "tout le monde est rentré",
    distractors: ["il neige fort", "le chat est sorti", "on part en vacances"],
  },
  {
    passage: "Le four est chaud. Le gâteau va cuire.",
    prompt: "Qu'est-ce qui va cuire ?",
    answer: "le gâteau",
    distractors: ["la soupe", "le pain rassis", "les chaussettes"],
  },
];

export const LECTURE_QUOTIDIEN: QuizSeed[] = [
  {
    passage: "Il pleut ce matin. Léa prend son parapluie rouge.",
    prompt: "Quel temps fait-il ?",
    answer: "il pleut",
    distractors: ["il neige", "il fait soleil", "il vente"],
  },
  {
    passage: "Le bus arrive à huit heures. Nino ne veut pas le rater.",
    prompt: "À quelle heure arrive le bus ?",
    answer: "huit heures",
    distractors: ["neuf heures", "midi", "six heures"],
  },
  {
    passage: "On achète du pain à la boulangerie. Il est encore chaud.",
    prompt: "Où achète-t-on le pain ?",
    answer: "à la boulangerie",
    distractors: ["à la piscine", "à l'école", "à la gare"],
  },
  {
    passage: "Le feu est rouge. Les voitures s'arrêtent.",
    prompt: "Que font les voitures ?",
    answer: "elles s'arrêtent",
    distractors: ["elles accélèrent", "elles reculent", "elles klaxonnent"],
  },
  {
    passage: "On va à la piscine le mercredi. L'eau est un peu froide.",
    prompt: "Quel jour va-t-on à la piscine ?",
    answer: "mercredi",
    distractors: ["lundi", "samedi", "dimanche"],
  },
  {
    passage: "Le facteur apporte une lettre. Elle est pour maman.",
    prompt: "Pour qui est la lettre ?",
    answer: "maman",
    distractors: ["papa", "Léa", "le chat"],
  },
  {
    passage: "Il y a du vent. Les feuilles volent dans la rue.",
    prompt: "Que font les feuilles ?",
    answer: "elles volent",
    distractors: ["elles nagent", "elles dorment", "elles chantent"],
  },
  {
    passage: "On prend le train pour aller chez papi. Le voyage dure une heure.",
    prompt: "Combien de temps dure le voyage ?",
    answer: "une heure",
    distractors: ["un jour", "une minute", "un mois"],
  },
  {
    passage: "Le marché est ouvert. On achète des pommes et des poires.",
    prompt: "Qu'achète-t-on au marché ?",
    answer: "des pommes et des poires",
    distractors: ["des chaussures", "des livres", "des crayons"],
  },
  {
    passage: "La lune brille. Les étoiles sont nombreuses.",
    prompt: "Qu'est-ce qui brille ?",
    answer: "la lune",
    distractors: ["le soleil", "un lampadaire", "un phare"],
  },
  {
    passage: "Il fait froid dehors. On met un manteau.",
    prompt: "Pourquoi met-on un manteau ?",
    answer: "il fait froid",
    distractors: ["il fait chaud", "il pleut des bonbons", "c'est l'été"],
  },
  {
    passage: "Le match commence. L'équipe bleue a le ballon.",
    prompt: "Quelle équipe a le ballon ?",
    answer: "l'équipe bleue",
    distractors: ["l'équipe rouge", "l'équipe verte", "l'équipe jaune"],
  },
  {
    passage: "On traverse sur le passage. Les voitures attendent.",
    prompt: "Où traverse-t-on ?",
    answer: "sur le passage",
    distractors: ["au milieu de la route", "sur le toit", "dans le pré"],
  },
  {
    passage: "Le film dure deux heures. On mange du pop-corn.",
    prompt: "Combien de temps dure le film ?",
    answer: "deux heures",
    distractors: ["dix minutes", "un jour", "cinq secondes"],
  },
  {
    passage: "Il neige. Les enfants font un bonhomme de neige.",
    prompt: "Que font les enfants ?",
    answer: "un bonhomme de neige",
    distractors: ["un gâteau", "un château de sable", "un cerf-volant"],
  },
  {
    passage: "Léo a mal à la gorge. On va chez le médecin.",
    prompt: "Pourquoi va-t-on chez le médecin ?",
    answer: "Léo a mal à la gorge",
    distractors: ["Léo a faim", "Léo veut jouer", "Léo a perdu un gant"],
  },
];
